CREATE TABLE rooms (
    id         BIGINT        NOT NULL AUTO_INCREMENT,
    price      DECIMAL(12,2) NOT NULL DEFAULT 0,
    beds_count INT           NOT NULL DEFAULT 1,
    created_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
